### ISSUE TITLE
ValueError: upper_edge_hertz must not be larger than the Nyquist frequency (sample_rate / 2). Got: 7500.0 for sample_rate: 8000

### ISSUE THREAD

**Issue by vinnitu** [biemster/asr#1]
Hello!

I have received error when trying to run dictation.py

Can you share properly formated wav file (sample.wav)?

**Comment by biemster** [comment]
You could use any mp3 downloaded from youtube, and convert it to wav using:
`$ ffmpeg -t 00:00:04.00 -i input.mp3 sample.wav`

Or use any other wav file with a sample rate higher than 7500*2 = 15kHz
